version: "3.7"
services:

  nats1:
    image: nats:2.7.2-scratch
    ports: 
      - 4222:4222
      - 8222:8222
      - 8502:8502
    networks:
      - natsnet
    volumes:
      - ./config/nats.conf:/etc/nats/nats.conf  
    command: "-config /etc/nats/nats.conf --server_name nats1"
  nats2:
    image: nats:2.7.2-scratch
    ports: 
      - 14222:4222
      - 18222:8222
    networks:
      - natsnet
    volumes:
      - ./config/nats.conf:/etc/nats/nats.conf  
    command: "-config /etc/nats/nats.conf --server_name nats2"
#    command: "-js --server_name nats2 --cluster_name nats --cluster nats://0.0.0.0:6222 --routes nats://nats1:6222,nats://nats3:6222"
  nats3:
    image: nats:2.7.2-scratch
    ports: 
      - 24222:4222
      - 28222:8222
    networks:
      - natsnet
    volumes:
      - ./config/nats.conf:/etc/nats/nats.conf  
    command: "-config /etc/nats/nats.conf --server_name nats3"
#    command: "-js --server_name nats3 --cluster_name nats --cluster nats://0.0.0.0:6222 --routes nats://nats1:6222,nats://nats2:6222"

  nats-streaming1:
    image: nats-streaming:0.19
    depends_on: 
      - nats1
      - nats2
      - nats3
    networks:
      - natsnet
    volumes: 
      - ./data/nats-streaming1/data:/workspace/data
      - ./data/nats-streaming1/log:/workspace/log
    command: "--store file --dir /workspace/data -clustered --cluster_log_path /workspace/log --cluster_id cluster1 --cluster_node_id nats-streaming1  --cluster_peers nats-streaming2,nats-streaming3 --cluster_sync --nats_server nats://nats1:4222,nats://nats2:4222,nats://nats3:4222"

  nats-streaming2:
    image: nats-streaming:0.19
    depends_on: 
      - nats1
      - nats2
      - nats3
    networks:
      - natsnet
    volumes: 
      - ./data/nats-streaming2/data:/workspace/data
      - ./data/nats-streaming2/log:/workspace/log
    command: "--store file --dir /workspace/data -clustered --cluster_log_path /workspace/log --cluster_id cluster1 --cluster_node_id nats-streaming2 --cluster_peers nats-streaming1,nats-streaming3 --cluster_sync --nats_server nats://nats1:4222,nats://nats2:4222,nats://nats3:4222"

  nats-streaming3:
    image: nats-streaming:0.19
    depends_on: 
      - nats1
      - nats2
      - nats3
    networks:
      - natsnet
    volumes: 
      - ./data/nats-streaming3/data:/workspace/data
      - ./data/nats-streaming3/log:/workspace/log
    command: "--store file --dir /workspace/data -clustered --cluster_log_path /workspace/log --cluster_id cluster1 --cluster_node_id nats-streaming3 --cluster_peers nats-streaming1,nats-streaming2 --cluster_sync --nats_server nats://nats1:4222,nats://nats2:4222,nats://nats3:4222"

networks:
  natsnet:
    name: natsnet
    driver: bridge
